set_option maxRecDepth 100000
-- Generated by gen.py. Rationals are pairs (numerator, denominator) of naturals, denominators positive.
abbrev Q := Nat × Nat

def norm (a : Q) : Q := let g := Nat.gcd a.1 a.2; if g = 0 then a else (a.1 / g, a.2 / g)
def qadd (a b : Q) : Q := norm (a.1 * b.2 + b.1 * a.2, a.2 * b.2)
def qmul (a b : Q) : Q := norm (a.1 * b.1, a.2 * b.2)
def qdiv (a b : Q) : Q := norm (a.1 * b.2, a.2 * b.1)
-- a - b, defined when b <= a
def qsub (a b : Q) : Q := norm (a.1 * b.2 - b.1 * a.2, a.2 * b.2)
def qlt (a b : Q) : Bool := a.1 * b.2 < b.1 * a.2
def qpow (a : Q) : Nat → Q
  | 0 => (1, 1)
  | k + 1 => qmul a (qpow a k)

-- 2 * (sum_{j<n} z^(2j+1)/(2j+1) + z^(2n+1) / ((2n+1)(1 - z^2)))
def atanhSum (z : Q) : Nat → Q
  | 0 => (0, 1)
  | j + 1 => qadd (atanhSum z j) (qdiv (qpow z (2 * j + 1)) (2 * j + 1, 1))
def twoAtanhUp (z : Q) (n : Nat) : Q :=
  qmul (2, 1) (qadd (atanhSum z n) (qdiv (qpow z (2 * n + 1)) (qmul (2 * n + 1, 1) (qsub (1, 1) (qmul z z)))))

-- halve x until x <= 2, counting the halvings (fuel bounds the loop)
def halve (x : Q) (k : Nat) : Nat → Q × Nat
  | 0 => (x, k)
  | f + 1 => if qlt (2, 1) x then halve (norm (x.1, 2 * x.2)) (k + 1) f else (x, k)

def lnUp (x : Q) : Q :=
  let p := halve x 0 64
  let y := p.1
  let base := qmul (p.2, 1) (twoAtanhUp (1, 3) 30)
  if qlt (1, 1) y then qadd base (twoAtanhUp (qdiv (qsub y (1, 1)) (qadd y (1, 1))) 30) else base

def rankSum (h : List (Nat × Nat)) : Nat := h.foldl (fun acc p => acc + p.1 * p.2) 0

-- moment bound: every a * L_w < 1, every w < m, and sum n w / (m (1 - a L_w)) < W
def momentOK (h : List (Nat × Nat)) (a : Q) (m W : Nat) : Bool :=
  let step := fun (acc : Bool × Q) (p : Nat × Nat) =>
    let w := p.1; let n := p.2
    let l := lnUp (m, w)
    let al := qmul a l
    let ok := acc.1 && (w < m) && qlt al (1, 1)
    if ok then (true, qadd acc.2 (qdiv (n * w, 1) (qmul (m, 1) (qsub (1, 1) al)))) else (false, acc.2)
  let r := h.foldl step (true, (0, 1))
  r.1 && qlt r.2 (W, 1)

def qmax (a b : Q) : Q := if qlt a b then b else a
def qmin (a b : Q) : Q := if qlt a b then a else b

-- The assembly of scripts/certificate_round3.py (crude guard), for given savings a_b, a_c, beta and the chosen
-- eps, x, kappa: every constraint is strict and every cost margin exceeds kappa. C1 = 1 + m_c ln s_c + 1 is
-- replaced by the check that the given C1 bounds 2 + m_c * (upper bound of ln s_c).
def kappaOK (ab ac beta eps x c1 kappa : Q) (mc sc : Nat) : Bool :=
  let gl : Q := (1, 10000000000000000)
  let one : Q := (1, 1)
  let tau := qsub one ab
  let sigma := qsub one ac
  let chi := qadd tau (qmul (qsub one beta) (if qlt tau sigma then qsub sigma tau else (0, 1)))
  let leaf := qadd sigma (qmul beta (qsub one sigma))
  let lam := qadd (qmax (qmax tau sigma) chi) gl
  let lamp := qadd (qmax lam leaf) gl
  let delta := qdiv (1, 10000000000000000000000) x
  let poly := qmul (qadd one x) delta
  let c1ok := !(qlt c1 (qadd (2, 1) (qmul (mc, 1) (lnUp (sc, 1)))))
  let cons := qlt lamp one && qlt (qmul eps (qsub (2, 1) lamp)) one
    && qlt (qmul eps c1) (qadd one x) && qlt (qadd (qmul (2, 1) eps) eps) (qadd one x)
    && qlt (qsub (qmul (2, 1) eps) one) (qmul lamp eps) && qlt eps one && qlt delta (1, 8)
  let margins := [qsub one eps, qmul eps (qsub one lamp), qsub (qsub one eps) poly, eps,
                  qmul (qmax eps (qsub one eps)) (qsub one tau)]
  c1ok && cons && margins.all (fun g => qlt kappa g)

-- bit interchange, staircase entrance corner
def bitHist : List (Nat × Nat) := [(1, 1690297301), (3, 1356586), (5, 354200), (7, 3580962), (9, 1526602), (11, 5093396), (13, 2164162), (15, 7948248), (17, 8476006), (18, 6272882), (19, 1639946), (21, 6906900), (23, 61280142), (439, 6272882), (483, 61280142), (485, 545468), (487, 173558), (489, 293986), (491, 580888), (493, 14168), (495, 322322), (497, 17710), (499, 1129898), (501, 127512), (503, 410872), (505, 99176), (507, 1186570), (509, 340032), (511, 322322), (513, 106260), (515, 1583274), (517, 626934), (519, 2854852), (521, 13711082), (523, 4629394), (525, 5653032), (527, 6233920)]
theorem bit_rank_sum : rankSum bitHist = 57403754177 := by decide
theorem bit_moment : momentOK bitHist (31987, 500000000) 529 108516254 = true := by decide
-- bit interchange, round-six entrance corner
def bitplainHist : List (Nat × Nat) := [(1, 1803209177), (3, 1356586), (5, 354200), (7, 3580962), (9, 1526602), (11, 5093396), (13, 2164162), (15, 7948248), (17, 8476006), (19, 1639946), (21, 6906900), (23, 61280142), (439, 6272882), (483, 61280142), (485, 545468), (487, 173558), (489, 293986), (491, 580888), (493, 14168), (495, 322322), (497, 17710), (499, 1129898), (501, 127512), (503, 410872), (505, 99176), (507, 1186570), (509, 340032), (511, 322322), (513, 106260), (515, 1583274), (517, 626934), (519, 2854852), (521, 13711082), (523, 4629394), (525, 5653032), (527, 6233920)]
theorem bitplain_rank_sum : rankSum bitplainHist = 57403754177 := by decide
theorem bitplain_moment : momentOK bitplainHist (12599, 200000000) 529 108516254 = true := by decide
-- complex interchange (round six)
def cxHist : List (Nat × Nat) := [(1, 184811440), (2, 107199136), (3, 50583808), (4, 53478128), (5, 33031680), (6, 27611408), (7, 14767104), (8, 20195472), (9, 6217728), (10, 14119424), (11, 5051904), (12, 13742960), (13, 4663296), (14, 14864256), (15, 4849504), (16, 13014320), (17, 10196912), (18, 33371712), (19, 13601280), (20, 22774048), (22, 44038192), (23, 16479408), (24, 4048), (529, 8193152), (552, 199193984)]
theorem cx_rank_sum : rankSum cxHist = 119453132304 := by decide
theorem cx_moment : momentOK cxHist (36926111, 500000000000) 576 207387136 = true := by decide
-- assembly: kappa = 1599247689723/25000000000000000 with the two savings above
theorem kappa_assembly : kappaOK (31987, 500000000) (36926111, 500000000000) (1, 1000) (9999360300924109, 10000000000000000) (14695, 1) (14694, 1) (1599247689723, 25000000000000000) 576 119453132304 = true := by decide +kernel
-- assembly: kappa = 6299103187973/100000000000000000 with the savings bitplain and cx above
theorem kappaplain_assembly : kappaOK (12599, 200000000) (36926111, 500000000000) (1, 1000) (9999370089681201, 10000000000000000) (14695, 1) (14694, 1) (6299103187973, 100000000000000000) 576 119453132304 = true := by decide +kernel
