set_option maxRecDepth 100000
-- Generated by gen.py. Rationals are pairs (numerator, denominator) of naturals, denominators positive.
abbrev Q := Nat × Nat

def norm (a : Q) : Q := let g := Nat.gcd a.1 a.2; if g = 0 then a else (a.1 / g, a.2 / g)
def qadd (a b : Q) : Q := norm (a.1 * b.2 + b.1 * a.2, a.2 * b.2)
def qmul (a b : Q) : Q := norm (a.1 * b.1, a.2 * b.2)
def qdiv (a b : Q) : Q := norm (a.1 * b.2, a.2 * b.1)
-- a - b, defined when b <= a
def qsub (a b : Q) : Q := norm (a.1 * b.2 - b.1 * a.2, a.2 * b.2)
def qlt (a b : Q) : Bool := a.1 * b.2 < b.1 * a.2
def qpow (a : Q) : Nat → Q
  | 0 => (1, 1)
  | k + 1 => qmul a (qpow a k)

-- 2 * (sum_{j<n} z^(2j+1)/(2j+1) + z^(2n+1) / ((2n+1)(1 - z^2)))
def atanhSum (z : Q) : Nat → Q
  | 0 => (0, 1)
  | j + 1 => qadd (atanhSum z j) (qdiv (qpow z (2 * j + 1)) (2 * j + 1, 1))
def twoAtanhUp (z : Q) (n : Nat) : Q :=
  qmul (2, 1) (qadd (atanhSum z n) (qdiv (qpow z (2 * n + 1)) (qmul (2 * n + 1, 1) (qsub (1, 1) (qmul z z)))))

-- halve x until x <= 2, counting the halvings (fuel bounds the loop)
def halve (x : Q) (k : Nat) : Nat → Q × Nat
  | 0 => (x, k)
  | f + 1 => if qlt (2, 1) x then halve (norm (x.1, 2 * x.2)) (k + 1) f else (x, k)

def lnUp (x : Q) : Q :=
  let p := halve x 0 64
  let y := p.1
  let base := qmul (p.2, 1) (twoAtanhUp (1, 3) 30)
  if qlt (1, 1) y then qadd base (twoAtanhUp (qdiv (qsub y (1, 1)) (qadd y (1, 1))) 30) else base

def rankSum (h : List (Nat × Nat)) : Nat := h.foldl (fun acc p => acc + p.1 * p.2) 0

-- moment bound: every a * L_w < 1, every w < m, and sum n w / (m (1 - a L_w)) < W
def momentOK (h : List (Nat × Nat)) (a : Q) (m W : Nat) : Bool :=
  let step := fun (acc : Bool × Q) (p : Nat × Nat) =>
    let w := p.1; let n := p.2
    let l := lnUp (m, w)
    let al := qmul a l
    let ok := acc.1 && (w < m) && qlt al (1, 1)
    if ok then (true, qadd acc.2 (qdiv (n * w, 1) (qmul (m, 1) (qsub (1, 1) al)))) else (false, acc.2)
  let r := h.foldl step (true, (0, 1))
  r.1 && qlt r.2 (W, 1)

def qmax (a b : Q) : Q := if qlt a b then b else a
def qmin (a b : Q) : Q := if qlt a b then a else b

-- The assembly of scripts/certificate_round3.py (crude guard), for given savings a_b, a_c, beta and the chosen
-- eps, x, kappa: every constraint is strict and every cost margin exceeds kappa. C1 = 1 + m_c ln s_c + 1 is
-- replaced by the check that the given C1 bounds 2 + m_c * (upper bound of ln s_c).
def kappaOK (ab ac beta eps x c1 kappa : Q) (mc sc : Nat) : Bool :=
  let gl : Q := (1, 10000000000000000)
  let one : Q := (1, 1)
  let tau := qsub one ab
  let sigma := qsub one ac
  let chi := qadd tau (qmul (qsub one beta) (if qlt tau sigma then qsub sigma tau else (0, 1)))
  let leaf := qadd sigma (qmul beta (qsub one sigma))
  let lam := qadd (qmax (qmax tau sigma) chi) gl
  let lamp := qadd (qmax lam leaf) gl
  let delta := qdiv (1, 10000000000000000000000) x
  let poly := qmul (qadd one x) delta
  let c1ok := !(qlt c1 (qadd (2, 1) (qmul (mc, 1) (lnUp (sc, 1)))))
  let cons := qlt lamp one && qlt (qmul eps (qsub (2, 1) lamp)) one
    && qlt (qmul eps c1) (qadd one x) && qlt (qadd (qmul (2, 1) eps) eps) (qadd one x)
    && qlt (qsub (qmul (2, 1) eps) one) (qmul lamp eps) && qlt eps one && qlt delta (1, 8)
  let margins := [qsub one eps, qmul eps (qsub one lamp), qsub (qsub one eps) poly, eps,
                  qmul (qmax eps (qsub one eps)) (qsub one tau)]
  c1ok && cons && margins.all (fun g => qlt kappa g)

-- E3(x) = 1 + x + x^2/(2(1 - x/3)), an upper bound of exp x on [0, 3)
def expUp3 (x : Q) : Q :=
  qadd (qadd (1, 1) x) (qdiv (qmul x x) (qmul (2, 1) (qsub (1, 1) (qdiv x (3, 1)))))

-- cover moment: every w < m, every a L_w < 3, and sum n w E3(a L_w) + fb E3(a L_1) < W m, where fb counts the
-- fallback children of width 1 (the bad fraction times 32 m^2 per edge; 0 on the complex side)
def momentCoverOK (h : List (Nat × Nat)) (a : Q) (m W : Nat) (fb : Q) : Bool :=
  let step := fun (acc : Bool × Q) (p : Nat × Nat) =>
    let w := p.1; let n := p.2
    let al := qmul a (lnUp (m, w))
    let ok := acc.1 && (w < m) && qlt al (3, 1)
    if ok then (true, qadd acc.2 (qmul (n * w, 1) (expUp3 al))) else (false, acc.2)
  let r := h.foldl step (true, (0, 1))
  let a1 := qmul a (lnUp (m, 1))
  r.1 && qlt a1 (3, 1) && qlt (qadd r.2 (qmul fb (expUp3 a1))) (W * m, 1)

-- stopped saving: ab = (1 - theta) a + theta aold, aold < a, and ab < theta < 1 - ab
def stopOK9 (a aold theta ab : Q) : Bool :=
  let v := qadd (qmul (qsub (1, 1) theta) a) (qmul theta aold)
  v.1 * ab.2 == ab.1 * v.2 && qlt aold a && qlt ab theta && qlt (qadd ab theta) (1, 1)

-- prod_{i=1}^{k} (4^i - 1)
def prod4 : Nat → Nat
  | 0 => 1
  | k + 1 => prod4 k * (4 ^ (k + 1) - 1)

-- finite bridge of the complex cover over the group of order V = 2^(m-1+(n-1)^2) prod_{i<n} (4^i - 1), n = m/2:
-- the literal router charge is below E (literal_scalar_guard), the semantic guard holds, dc is the least n with
-- m^n > 2 r^n, wc is the bit length of W, and the external row reserve 51 (dc wc + reserve) / 25 < degree holds
-- (row_product_gap)
def bridgeOK (m r W0 s0 v h R cAdd mops dc wc reserve degree : Nat) : Bool :=
  let n := m / 2
  let V := 2 ^ (m - 1 + (n - 1) * (n - 1)) * prod4 (n - 1)
  let N := V * v
  let W := V * W0
  let s := V * s0
  let loc := 4 * (cAdd + v) + 10 * v + 4 * h * v + 4 * h * h + 8 * h + 8 + 2 * h + 8 * R * v * (mops + 16) + 32 * v
  let logical := 3 * V * loc + 8 * W + 4 * N + 8 * m * R * V
  let G := 64 * (m + 1) ^ 3 * (logical + 1) * (W + 1) ^ 2
  let E := 64 * (W + m + G + 1) ^ 3
  let charge := 2 * G * W * W + 8 * s + 4 * W + 4 + 32 * m
  let B := s + E
  (0 < r) && (r < m) && (charge < E) && (s + E ≤ 2 * B * (m - r)) && (2 * B + 18 < 32 * m * B * B)
    && (0 < dc) && (2 * r ^ dc < m ^ dc) && (dc == 1 || m ^ (dc - 1) ≤ 2 * r ^ (dc - 1))
    && (0 < wc) && (2 ^ (wc - 1) ≤ W) && (W < 2 ^ wc)
    && (51 * (dc * wc + reserve) < 25 * degree)

-- PR #144's semantic assembly at a = min(ab, (1 - beta) ac - gap): the 38 strict rows that do not come from the
-- bridge, the 7 cost margins above kappa, and kappa within 10^-10 below the minimum margin eps q
def assemblyOK (ab ac beta eta gap kappa : Q) : Bool :=
  let one : Q := (1, 1)
  let a := qmin ab (qsub (qmul (qsub one beta) ac) gap)
  let b := ac
  let tau := qsub one a
  let sigma := qsub one b
  let q := qmul a (qsub one (qmul (2, 1) eta))
  let lp := qsub one q
  let lam := qdiv (qadd tau lp) (2, 1)
  let c := qmul q (qadd one eta)
  let eps := qdiv (qsub one eta) (qadd (qadd one c) q)
  let mn := qmul eps q
  let r := qdiv (qadd mn (qsub one eps)) (2, 1)
  let delta := qdiv eta (8, 1)
  let internal := if qlt tau sigma then qadd tau (qmul (qsub one beta) (qsub sigma tau)) else tau
  let leaf := qadd sigma (qmul beta (qsub one sigma))
  let pos := fun (x : Q) => qlt (0, 1) x
  let rows := [pos a, qlt a b, qlt b (1, 32), pos beta, qlt beta one, qlt a (qmul (qsub one beta) b),
    pos q, qlt (qadd internal q) one, qlt (qadd leaf q) one, pos c, qlt c one, qlt q c,
    qlt tau lam, qlt sigma lam, qlt internal lam, qlt lam lp, qlt leaf lp, qlt (qsub one c) lp, pos q,
    pos eps, qlt eps one, qlt eps one, qlt (qmul eps (qadd one c)) one, pos (qmul eps c), qlt eps one,
    qlt (qadd eps delta) one, qlt delta r, qlt (qadd eps r) one, qlt (qdiv (qsub one r) (2, 1)) eps, qlt eps one,
    pos r, qlt r one, qlt r (1, 4), pos delta, qlt delta (1, 8), qlt a eps, qlt (qadd eps mn) one,
    qlt (qadd (qadd eps delta) mn) (qadd (8, 1) r)]
  let margins := [qsub one (qmul eps (qadd one c)), a, mn, a, qmin (qsub (qsub one eps) delta) (qsub r delta),
    qsub (qsub one eps) delta, eps]
  rows.length == 38 && rows.all id && margins.all (fun g => qlt kappa g) && qlt mn (qadd kappa (1, 10000000000))

-- bit side: witness 2 (round 7.1, jfstack, h=23) with gauge omission, PR #144 cover, m=69
def bitHist : List (Nat × Nat) := [(1, 180309), (2, 220550), (3, 29124), (4, 39345), (5, 18756), (6, 5517), (7, 1827), (8, 3288), (9, 2016), (10, 582), (11, 939), (12, 699), (13, 930), (14, 1203), (15, 2922), (16, 3777), (17, 2373), (18, 1890), (19, 14259), (20, 498), (21, 1500), (22, 123), (48, 27), (51, 99), (54, 853), (57, 3797), (60, 1287), (63, 1595), (66, 1760)]
theorem bit_rank_sum : rankSum bitHist = 2160160 := by decide +kernel
theorem bit_moment : momentCoverOK bitHist (116809507, 250000000000) 69 31336 (82551169440, 10000000000000000) = true := by decide +kernel
theorem bit_stopped : stopOK9 (116809507, 250000000000) (384599, 10000000000) (1, 1000) (29175578117, 62500000000000) = true := by decide +kernel
-- complex side: PR #144 complex inventory (icekylinx, paired cubes on the PR #117 DAG, h=24)
def cxHist : List (Nat × Nat) := [(1, 79374), (2, 81787), (3, 34704), (4, 29763), (5, 22455), (6, 8535), (7, 7929), (8, 7881), (9, 3603), (10, 5829), (11, 3261), (12, 3291), (13, 2028), (14, 6972), (15, 2478), (16, 6789), (17, 4794), (18, 1194), (19, 11760), (20, 11880), (21, 2640), (22, 2712), (60, 4840)]
theorem cx_rank_sum : rankSum cxHist = 2153528 := by decide +kernel
theorem cx_moment : momentCoverOK cxHist (4856569, 10000000000) 72 29937 (0, 1) = true := by decide +kernel
theorem cx_bridge : bridgeOK 72 60 29937 2153528 1760 24 26417 24767 49424 4 2571 10161 70000 = true := by decide +kernel
-- assembly: kappa = 2331869/5000000000
theorem kappa_assembly : assemblyOK (29175578117, 62500000000000) (4856569, 10000000000) (1, 1000000) (1, 100000000) (1, 10000000000) (2331869, 5000000000) = true := by decide +kernel
